/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaGUI;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author taniv
 */
public class editBirthdate extends javax.swing.JFrame {
     String ID;
    /**
     * Creates new form editBirthdate
     */
    public editBirthdate() throws IOException {
        initComponents();
        this.setResizable(false);
        this.setSize(400,400);
        password.setEchoChar('*');
        for (int year=2024;year>=1900;year--){
            birthdateYear.add(String.valueOf(year));
        }
        for (int month=1;month<=12;month++){
            birthdateMonth.add(String.valueOf(month));
        }
        for (int day=1;day<=31;day++){
            birthdateDay.add(String.valueOf(day));
        }

    }
    
    public editBirthdate(String uID){
        initComponents();
        this.setResizable(false);
        this.setSize(400,400);
        password.setEchoChar('*');
        for (int year=2024;year>=1900;year--){
            birthdateYear.add(String.valueOf(year));
        }
        for (int month=1;month<=12;month++){
            birthdateMonth.add(String.valueOf(month));
        }
        for (int day=1;day<=31;day++){
            birthdateDay.add(String.valueOf(day));
        }
        ID = uID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doneChange = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        birthdateYear = new java.awt.Choice();
        birthdateMonth = new java.awt.Choice();
        birthdateDay = new java.awt.Choice();
        showPassword = new javax.swing.JCheckBox();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Change your Birth Date");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter your new birth date and current password");

        doneChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doneChange.setText("Done");
        doneChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneChangeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Current Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("New Birth Date");

        password.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaGUI/images/back arrow .png"))); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(birthdateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(birthdateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(birthdateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(showPassword)
                        .addGap(11, 11, 11)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(doneChange, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(backButton)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthdateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPassword)
                .addGap(18, 18, 18)
                .addComponent(doneChange, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneChangeActionPerformed
        try {
            int day = 0;
            switch (birthdateMonth.getSelectedItem()){
                case "1","3","5","7","8","10","12":
                    day = 31;
                    break;
                case "4","6","9","11":
                    day =30;
                    break;
                case "2":
                    if (((Integer.parseInt(birthdateYear.getSelectedItem())%4==0) & !(Integer.parseInt(birthdateYear.getSelectedItem())%100==0))|| (Integer.parseInt(birthdateYear.getSelectedItem())%400==0)){
                        day = 29;
                        break;
                    }
                    else{
                        day = 28;
                    }
            }
            txtToArray approvalList = new txtToArray ();
            String [][] approvalArray = approvalList.array("ApprovalList.txt");
            System.out.println(Arrays.deepToString(approvalArray));
            displayUserProfile displayProfile = new displayUserProfile();
            int userIndex = displayProfile.profileIndex(ID);
            System.out.println(userIndex);
            String [] userProfile = approvalArray[userIndex];
            System.out.println(Arrays.toString(userProfile));
            
            if(password.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please enter all required field","Warning Message",JOptionPane.WARNING_MESSAGE);
            }
            else if (Integer.parseInt(birthdateDay.getSelectedItem())>day){
                JOptionPane.showMessageDialog(null, "Please enter a valid date", "Invalid Date", JOptionPane.WARNING_MESSAGE);
            }
            else if (!password.getText().equals(userProfile[3])){
                JOptionPane.showMessageDialog(null,"Please enter a correct password","Incorrect Password",JOptionPane.WARNING_MESSAGE);
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Birth date is changed","Details changed",JOptionPane.INFORMATION_MESSAGE);
                dispose();
                profile Profile = new profile(ID);
                String newBirthdate = birthdateYear.getSelectedItem()+"-"+birthdateMonth.getSelectedItem()+"-"+birthdateDay.getSelectedItem();
                Profile.birthDate.setText(newBirthdate);
                Profile.setVisible(true);
                approvalArray[userIndex][4] = newBirthdate;
                BufferedWriter writer = new BufferedWriter(new FileWriter("ApprovalList.txt"));
                for (int i=0;i<approvalArray.length;i++){
                    writer.write(approvalArray[i][0]+","+approvalArray[i][1]+","+approvalArray[i][2]+","+approvalArray[i][3]+","+approvalArray[i][4]+","+approvalArray[i][5]+","+approvalArray[i][6]+","+approvalArray[i][7]+"\n");
                }
                writer.close();
                
            }
        } catch (IOException ex) {
            Logger.getLogger(editBirthdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doneChangeActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if(showPassword.isSelected()){
            password.setEchoChar((char)0);
        }
        else{
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        
    }//GEN-LAST:event_passwordActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            profile Profile = new profile(ID);
            Profile.show();
        } catch (IOException ex) {
            Logger.getLogger(editEmail.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editBirthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editBirthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editBirthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editBirthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new editBirthdate().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(editBirthdate.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private java.awt.Choice birthdateDay;
    private java.awt.Choice birthdateMonth;
    private java.awt.Choice birthdateYear;
    private javax.swing.JButton doneChange;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables
}
