/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaGUI;

import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author taniv
 */
public class residentInterface extends javax.swing.JFrame {
    
    String residentID;

    /**
     * Creates new form residentInterface
     */
    public residentInterface() {
        initComponents();
        this.setSize(480,360);
        this.setResizable(false);
        
    }
    
    public residentInterface(String userID){
        initComponents();
        residentID = userID;
        this.setSize(480,360);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPayment = new javax.swing.JButton();
        updateDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaGUI/images/bill .png"))); // NOI18N
        viewPayment.setText("View Payment Records");
        viewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentActionPerformed(evt);
            }
        });

        updateDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaGUI/images/personal-information-interface-symbol .png"))); // NOI18N
        updateDetails.setText("View Personal Details");
        updateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("WELCOME BACK");

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaGUI/images/log-out.png"))); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(updateDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(viewPayment)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(updateDetails)
                .addGap(29, 29, 29)
                .addComponent(viewPayment)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentActionPerformed
        residentViewPayment view_payment= new residentViewPayment(residentID);
        String [][] billArray;
        txtToArray billList = new txtToArray();
        DefaultTableModel bill_table = (DefaultTableModel)view_payment.billTable.getModel();
        boolean hasRecord = false;
        try {
            billArray = billList.array("BillList.txt");
            for (int i =1;i<billArray.length;i++){
                if (billArray[i][1].equals(residentID)){
                    hasRecord = true;
                }
                
            }
            if (hasRecord){
                view_payment.show();
                dispose();
            }
            
            else{
                JOptionPane.showMessageDialog(null,"No payment record","Payment record unavailable",JOptionPane.INFORMATION_MESSAGE);        
            }
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(residentViewPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_viewPaymentActionPerformed

    private void updateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsActionPerformed

        try {
            profile Profile = new profile(residentID);
            Profile.setVisible(true);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(residentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            dispose();

    }//GEN-LAST:event_updateDetailsActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int logoutConfirmation = JOptionPane.showConfirmDialog(null,"Are you sure to log out?","Log Out Confirmation",JOptionPane.YES_NO_OPTION);
        System.out.println(logoutConfirmation);
        if (logoutConfirmation==0){
            mainMenu main_menu;
            try {
                main_menu = new mainMenu();
                main_menu.show();
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(residentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            dispose();


        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(residentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(residentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(residentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(residentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new residentInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton updateDetails;
    private javax.swing.JButton viewPayment;
    // End of variables declaration//GEN-END:variables
}
